<?php 
if( function_exists('acf_add_local_field_group') ):

     acf_add_local_field_group( array(
          'key' => 'group_65a654890a9a7',
          'title' => 'B | Facts & Figures',
          'fields' => array(
               array(
                    'key' => 'field_65a6554cd527e',
                    'label' => 'Image',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'wpml_cf_preferences' => 1,
                    'return_format' => 'url',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
               ),
               array(
                    'key' => 'field_65a65489e8149',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'wpml_cf_preferences' => 2,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
               ),
               array(
                    'key' => 'field_65a654a2e814a',
                    'label' => 'Facts',
                    'name' => 'facts',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'wpml_cf_preferences' => 1,
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Eintrag hinzufügen',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                         array(
                              'key' => 'field_65a654b3e814b',
                              'label' => 'Icon',
                              'name' => 'icon',
                              'aria-label' => '',
                              'type' => 'image',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '30',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'wpml_cf_preferences' => 1,
                              'return_format' => 'url',
                              'library' => 'all',
                              'min_width' => '',
                              'min_height' => '',
                              'min_size' => '',
                              'max_width' => '',
                              'max_height' => '',
                              'max_size' => '',
                              'mime_types' => '',
                              'preview_size' => 'medium',
                              'parent_repeater' => 'field_65a654a2e814a',
                         ),
                         array(
                              'key' => 'field_65a654bfe814c',
                              'label' => 'Information',
                              'name' => 'information',
                              'aria-label' => '',
                              'type' => 'group',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '70',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'wpml_cf_preferences' => 1,
                              'layout' => 'block',
                              'sub_fields' => array(
                                   array(
                                        'key' => 'field_65a654cde814d',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                             'width' => '',
                                             'class' => '',
                                             'id' => '',
                                        ),
                                        'wpml_cf_preferences' => 2,
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                   ),
                                   array(
                                        'key' => 'field_65a654f2e814e',
                                        'label' => 'Text',
                                        'name' => 'text',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                             'width' => '',
                                             'class' => '',
                                             'id' => '',
                                        ),
                                        'wpml_cf_preferences' => 2,
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'rows' => 2,
                                        'placeholder' => '',
                                        'new_lines' => '',
                                   ),
                              ),
                              'parent_repeater' => 'field_65a654a2e814a',
                         ),
                    ),
               ),
               array(
                    'key' => 'field_65a65527d2368',
                    'label' => 'Button',
                    'name' => 'button',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'wpml_cf_preferences' => 1,
                    'return_format' => 'array',
               ),
          ),
          'location' => array(
               array(
                    array(
                         'param' => 'block',
                         'operator' => '==',
                         'value' => 'acf/facts',
                    ),
               ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
          'show_in_rest' => 0,
          'acfml_field_group_mode' => 'translation',
     ) );

endif;