<?php
if (function_exists("acf_add_local_field_group")):
    acf_add_local_field_group([
        "key" => "group_65a7cb7d9a6a1",
        "title" => "B | Gallery Slider",
        "fields" => [
            [
                "key" => "field_6863f96698941",
                "label" => "Title",
                "name" => "title",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 2,
                "default_value" => "",
                "maxlength" => "",
                "allow_in_bindings" => 0,
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_6863fe7164142",
                "label" => "Description",
                "name" => "description",
                "aria-label" => "",
                "type" => "textarea",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 2,
                "default_value" => "",
                "maxlength" => "",
                "allow_in_bindings" => 0,
                "rows" => "3",
                "placeholder" => "",
                "new_lines" => "",
            ],
            [
                "key" => "field_65a7cb7d1bff1",
                "label" => "Images",
                "name" => "images",
                "aria-label" => "",
                "type" => "gallery",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 1,
                "return_format" => "url",
                "library" => "all",
                "min" => "",
                "max" => "",
                "min_width" => "",
                "min_height" => "",
                "min_size" => "",
                "max_width" => "",
                "max_height" => "",
                "max_size" => "",
                "mime_types" => "",
                "insert" => "append",
                "preview_size" => "medium",
            ],
            [
                "key" => "field_6863f96f98942",
                "label" => "Flickr Link",
                "name" => "flickr_link",
                "aria-label" => "",
                "type" => "link",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 1,
                "return_format" => "array",
                "allow_in_bindings" => 0,
            ],
        ],
        "location" => [
            [
                [
                    "param" => "block",
                    "operator" => "==",
                    "value" => "acf/gallery-slider",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "",
        "show_in_rest" => 0,
        "acfml_field_group_mode" => "translation",
    ]);
endif;
