<?php
if (function_exists("acf_add_local_field_group")):
    acf_add_local_field_group([
        "key" => "group_65a693eac935a",
        "title" => "B | Ticket",
        "fields" => [
            [
                "key" => "field_65a693ebfce12",
                "label" => "Title",
                "name" => "title",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 2,
                "default_value" => "",
                "maxlength" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_65a69473fce13",
                "label" => "Subtitle",
                "name" => "subtitle",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 2,
                "default_value" => "",
                "maxlength" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_65a6948efce14",
                "label" => "Content",
                "name" => "content",
                "aria-label" => "",
                "type" => "wysiwyg",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 2,
                "default_value" => "",
                "tabs" => "all",
                "toolbar" => "basic",
                "media_upload" => 0,
                "delay" => 0,
            ],
            [
                "key" => "field_65a694b9fce15",
                "label" => "Price",
                "name" => "price",
                "aria-label" => "",
                "type" => "group",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 1,
                "layout" => "block",
                "sub_fields" => [
                    [
                        "key" => "field_65a694ddfce16",
                        "label" => "Pricetag",
                        "name" => "pricetag",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "30",
                            "class" => "",
                            "id" => "",
                        ],
                        "wpml_cf_preferences" => 2,
                        "default_value" => "",
                        "maxlength" => "",
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                    ],
                    [
                        "key" => "field_65a694f6fce17",
                        "label" => "Price",
                        "name" => "price",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "30",
                            "class" => "",
                            "id" => "",
                        ],
                        "wpml_cf_preferences" => 2,
                        "default_value" => "",
                        "maxlength" => "",
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                    ],
                    [
                        "key" => "field_65a69505fce18",
                        "label" => "Currency",
                        "name" => "currency",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "20",
                            "class" => "",
                            "id" => "",
                        ],
                        "wpml_cf_preferences" => 2,
                        "default_value" => "",
                        "maxlength" => "",
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                    ],
                    [
                        "key" => "field_65a69535fce19",
                        "label" => "Subtext",
                        "name" => "subtext",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "20",
                            "class" => "",
                            "id" => "",
                        ],
                        "wpml_cf_preferences" => 2,
                        "default_value" => "",
                        "maxlength" => "",
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                    ],
                ],
            ],
            [
                "key" => "field_65a69554fce1a",
                "label" => "Register Interaction 1",
                "name" => "register_interaction_1",
                "aria-label" => "",
                "type" => "group",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "50",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 1,
                "layout" => "block",
                "sub_fields" => [
                    [
                        "key" => "field_65a69586fce1b",
                        "label" => "Text",
                        "name" => "text",
                        "aria-label" => "",
                        "type" => "textarea",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "wpml_cf_preferences" => 2,
                        "default_value" => "",
                        "maxlength" => "",
                        "rows" => 3,
                        "placeholder" => "",
                        "new_lines" => "",
                    ],
                    [
                        "key" => "field_65a6959ffce1c",
                        "label" => "Button",
                        "name" => "button",
                        "aria-label" => "",
                        "type" => "link",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "wpml_cf_preferences" => 1,
                        "return_format" => "",
                    ],
                ],
            ],
            [
                "key" => "field_65a695b6fce1d",
                "label" => "Register Interaction 2",
                "name" => "register_interaction_2",
                "aria-label" => "",
                "type" => "group",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "50",
                    "class" => "",
                    "id" => "",
                ],
                "wpml_cf_preferences" => 1,
                "layout" => "block",
                "sub_fields" => [
                    [
                        "key" => "field_65a695b6fce1e",
                        "label" => "Text",
                        "name" => "text",
                        "aria-label" => "",
                        "type" => "textarea",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "wpml_cf_preferences" => 2,
                        "default_value" => "",
                        "maxlength" => "",
                        "rows" => 3,
                        "placeholder" => "",
                        "new_lines" => "",
                    ],
                    [
                        "key" => "field_65a695b6fce1f",
                        "label" => "Button",
                        "name" => "button",
                        "aria-label" => "",
                        "type" => "link",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "wpml_cf_preferences" => 1,
                        "return_format" => "array",
                    ],
                ],
            ],
        ],
        "location" => [
            [
                [
                    "param" => "block",
                    "operator" => "==",
                    "value" => "acf/ticket",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "",
        "show_in_rest" => 0,
        "acfml_field_group_mode" => "translation",
    ]);
endif;
