<?php 
if( function_exists('acf_add_local_field_group') ):

     acf_add_local_field_group( array(
          'key' => 'group_65a79a8d57ba1',
          'title' => 'B | Program',
          'fields' => array(
               array(
                    'key' => 'field_65a79a8dbd444',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'wpml_cf_preferences' => 2,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
               ),
               array(
                    'key' => 'field_65a79c1dbd448',
                    'label' => 'Image',
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'wpml_cf_preferences' => 1,
                    'return_format' => 'url',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
               ),
               array(
                    'key' => 'field_65a79adfbd445',
                    'label' => 'Program Rows',
                    'name' => 'program_rows',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'wpml_cf_preferences' => 1,
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Eintrag hinzufügen',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                         array(
                              'key' => 'field_65a79ba7bd446',
                              'label' => 'Time',
                              'name' => 'time',
                              'aria-label' => '',
                              'type' => 'time_picker',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '20',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'wpml_cf_preferences' => 1,
                              'display_format' => 'H:i',
                              'return_format' => 'H:i',
                              'parent_repeater' => 'field_65a79adfbd445',
                         ),
                         array(
                              'key' => 'field_65a79bf3bd447',
                              'label' => 'Program Title',
                              'name' => 'program_title',
                              'aria-label' => '',
                              'type' => 'text',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '80',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'wpml_cf_preferences' => 2,
                              'default_value' => '',
                              'maxlength' => '',
                              'placeholder' => '',
                              'prepend' => '',
                              'append' => '',
                              'parent_repeater' => 'field_65a79adfbd445',
                         ),
                    ),
               ),
          ),
          'location' => array(
               array(
                    array(
                         'param' => 'block',
                         'operator' => '==',
                         'value' => 'acf/program',
                    ),
               ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
          'show_in_rest' => 0,
          'acfml_field_group_mode' => 'translation',
     ) );

endif;